// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEkM8oBRpQdbRQmFjVPzKIcfWdnif76A',
    appId: '1:30847850152:web:1abc49a70ab81f9bc5949d',
    messagingSenderId: '30847850152',
    projectId: 'intellicloud-f5a27',
    authDomain: 'intellicloud-f5a27.firebaseapp.com',
    storageBucket: 'intellicloud-f5a27.firebasestorage.app',
    measurementId: 'G-02Z8V5DDYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3BMA-YdkdTinzyx_sIWKYKpjU38rJkQ',
    appId: '1:30847850152:android:46cf28acbe6365fbc5949d',
    messagingSenderId: '30847850152',
    projectId: 'intellicloud-f5a27',
    storageBucket: 'intellicloud-f5a27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PRUIfvw2EEhOXkRImHsxCoFoK5c5yMg',
    appId: '1:30847850152:ios:abd80a6c65039f08c5949d',
    messagingSenderId: '30847850152',
    projectId: 'intellicloud-f5a27',
    storageBucket: 'intellicloud-f5a27.firebasestorage.app',
    iosBundleId: 'com.example.intellicloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PRUIfvw2EEhOXkRImHsxCoFoK5c5yMg',
    appId: '1:30847850152:ios:abd80a6c65039f08c5949d',
    messagingSenderId: '30847850152',
    projectId: 'intellicloud-f5a27',
    storageBucket: 'intellicloud-f5a27.firebasestorage.app',
    iosBundleId: 'com.example.intellicloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwEkM8oBRpQdbRQmFjVPzKIcfWdnif76A',
    appId: '1:30847850152:web:26a8baa01ed7bdefc5949d',
    messagingSenderId: '30847850152',
    projectId: 'intellicloud-f5a27',
    authDomain: 'intellicloud-f5a27.firebaseapp.com',
    storageBucket: 'intellicloud-f5a27.firebasestorage.app',
    measurementId: 'G-YEEMLNRWF4',
  );
}
